Make clearer "run ./configure" message

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -53,7 +53,10 @@ all:: ensureConfigured
 
 ensureConfigured:
 	@if [ ! -f $(BRICKOS_ROOT)/.configured.flg ]; then \
-		echo "brickOS builds not yet configured, please run ./configure then attempt the build" >&2; \
+		echo "" >&2; \
+		echo "ERROR- brickOS builds are not yet configured..." >&2; \
+		echo " Please run ./configure then re-attempt this build." >&2; \
+		echo "" >&2; \
 		exit 2; \
 	fi
 
